### ISSUE TITLE
Don't show email icon if email is empty

### ISSUE THREAD

**Issue by DonDiegoAA** [inspheric/nova-email-field#2]
Hello,

thank you for the clickableOnIndex() !

Perhaps a small improvement would be to not show the Email icon if the field is empty, and rather this dash — in the detail view as Nova does it by default.

**Comment by kitbs** [comment]
Hi, you're welcome.

The behaviour to display — if the email is empty is [already there](https://github.com/inspheric/nova-email-field/blob/48fe095f8771afc37625ad1ce263688331457b2d/resources/js/components/Email.vue#L23) but I think it didn't push to Packagist. It should be there now in v1.2.

Thanks
