### ISSUE TITLE
Renders to nothing in Nova 4

### ISSUE THREAD

**Issue by Synchro** [inspheric/nova-email-field#24]
This seems to have broken in Nova 4. When I set up an email field as a standard `Text` type, it appears fine, but when I switch it to this package, the field (including its title) is not rendered at all. I have seen similar effects after upgrading to Nova 4 with other packages too, so I suspect you're running into the same problem, though I don't know what it is.

**Comment by kitbs** [comment]
Nova 4 upgraded to Vue 3 and totally changed the way the fields are rendered. I have fixed this in a new release v2.0.0 at https://github.com/inspheric/nova-email-field/releases/tag/v2.0.0
